name: flutter_hotel_management
description: A new Flutter project.

version: 1.0.0+1
# When you change vesionName or versionCode, You also need to change below.
#versionName->1.0.0
#versionCode->1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  barcode_widget: 
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  encrypt: ^5.0.1
  equatable: ^2.0.5
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^9.5.0
  flutter_inappwebview: ^5.7.2+3
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^1.3.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.7
  get_it: ^7.2.0
  http: ^0.13.1
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  jwt_decode: ^0.3.1
  local_auth: ^1.1.1
  math_expressions: ^2.1.0
  openid_client: ^0.4.3
  package_info: ^2.0.0
  path_provider: ^2.0.9
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.4
  screenshot: ^1.2.3
  share_plus: ^4.0.4
  shared_preferences: ^2.0.5
  showcaseview: ^1.1.0
  syncfusion_flutter_datepicker: ^20.1.52
  url_launcher: ^6.0.3
  syncfusion_flutter_pdf: ^20.2.49
  sunmi_printer_plus: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  fast_i18n: ^5.12.6
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sarabun-Bold
      fonts:
        - asset: assets/fonts/fonts-sarabun/Sarabun-Bold.ttf
          weight: 700

    - family: Sarabun-SemiBold
      fonts:
        - asset: assets/fonts/fonts-sarabun/Sarabun-SemiBold.ttf
          weight: 600

    - family: Sarabun-Medium
      fonts:
        - asset: assets/fonts/fonts-sarabun/Sarabun-Medium.ttf
          weight: 500

    - family: Sarabun-Regular
      fonts:
        - asset: assets/fonts/fonts-sarabun/Sarabun-Regular.ttf
          weight: 400

    - family: DB_Ozone_X
      fonts:
        - asset: assets/fonts/fonts-db_ozone_x/DB_Ozone_X.ttf
          weight: 600

    - family: DB_Ozone_X_Med
      fonts:
        - asset: assets/fonts/fonts-db_ozone_x/DB_Ozone_X_Med.ttf
          weight: 500

    - family: DB_Ozone_X_Li
      fonts:
        - asset: assets/fonts/fonts-db_ozone_x/DB_Ozone_X_Li.ttf
          weight: 400

